### PR TITLE
Added gf to workflow

### PR DESCRIPTION
**Pull request by Anu-bhav**

### CODE REVIEW

**Review by x1mdev — COMMENTED** [review]
Going to test this new function today, @maverickNerd do you want to take a look as well?

**Comment by Anu-bhav** [comment]
No worries, I was planning on replacing eyewitness with aquatone also.

**Comment by maverickNerd** [comment]
We were using aquatone till the last commits, aquatone is having some issues on digitalocean servers, so we replaced it with eyewitness, will keep checking on aquatone status, if it starts working, we will replace agian.

**Comment by maverickNerd** [comment]
Looks good to me, merging it, thanks for the PR.

**Pull request merged**
